### PR TITLE
Import misc fixes by Marc

### PR DESCRIPTION
**Pull request by bosr**
Hi, thanks for that package!

In order to avoid fragmentation, here are some fixes by @marcrasi, along with a minor rewording in String extension, `hasMatch(pat:)` -> `matches(pattern:)`.

### CODE REVIEW

**Comment by bosr** [comment]
I also updated the Swift tools version to 5.1, as it gets picked by `swift-jupyter`.

**Comment by pcuenca** [comment]
Thanks!

> I also updated the Swift tools version to 5.1, as it gets picked by `swift-jupyter`.

Why is this necessary? As far as I can tell, swift-jupyter [is using version 4.2](https://github.com/google/swift-jupyter/blob/master/swift_kernel.py#L612) to `%install` packages.

**Comment by bosr** [comment]
Hi,

As far as I can tell, a Notebook that contains Swift 5 code is compiled correctly only if the `swift-tools-version` is `5` or `5.1`; it looks like setting the swift language version attribute at the end of a   Package.swift is not enough if tools version pre-dates the language version. This is briefly described [here](https://github.com/apple/swift-evolution/blob/master/proposals/0151-package-manager-swift-language-compatibility-version.md) 

> When building a package, we will always select the Swift language version that is most close to (but not exceeding) the major version of the Swift compiler in use.

Does that make sense?

On the other hand, your Package `swift-tools-version` did not actually need to be updated; do you want me to change it back to 4.2?

**Comment by pcuenca** [comment]
Sorry for the delay, I've been busy with other projects. Your explanation makes sense. Thanks for your patience!

**Comment by bosr** [comment]
No worries, thanks!

**Pull request merged**
